#!/bin/sh

scriptpath="$(readlink -f "$0")"
workdir="${scriptpath%/*}"
PATH="${workdir}:${PATH}"

. "${workdir}"/bootstrap-all.conf || exit 1

uname_m="$(uname -m)"

if [ "$(id -u)" != '0' ]; then
	echo "You need to run this script as root."
	exit 1
fi

if [ -z "$1" ]; then
	echo ">>> No arch specified. using '${uname_m}'."
	arch="${uname_m}"

else
	arch="$1"
fi

case "${arch}" in
	i486|i586|i686|x86_64)
	;;
	*)
		echo "Looks like '${arch}' is not supported. If the arch is valid consider reporting it upstream."
	;;
esac

if [ "${arch}" != "${uname_m}" ]; then
	crossarch="setarch ${arch}"
else
	crossarch=''
fi

lebuild init "${arch}"
${crossarch} lebuild build ${packages}

case " ${packages} " in
	*" mdadm "*)
		printf "\n\033[1;31m>>> WARNING:\033[0m Currently 'mdadm' is unable to auto-assemble raid, the exact reason \nis still unknown. If you use 'softraid' feature you may need to replace mdadm binary \nwith known-to-be-working one. We are working on the issue so the future releases \nshould have this issue resolved.\n\n"
	;;
esac
