#!/bin/bash
# -*- mode: shell-script; coding: utf-8-emacs-unix; sh-basic-offset: 8; indent-tabs-mode: t -*-

workdir="$(readlink -f $(dirname $0))"
. $workdir/core.sh || exit 1

if [[ -z $1 ]]; then
	die "You shouldn't run this."
fi

source="$1"
if [[ ! -z $2 ]]; then
	target="$initramfs_root/bin/$(basename $2)"
else
	target="$initramfs_root/bin/$(basename $source)"
fi

addbin() {
	dynamic_libs=`ldd $source | awk '{if (NF==4) print $3; if (NF==2) print $1}'`
	einfo "Adding $source..."
	if ! ldd $source >> /dev/null; then
		$sudo cp -p $source $target # static link file
	else
		$sudo cp -p $source $target # dynamic link file, copy dynamic library
		for lib in $dynamic_libs; do
			test -d ${initramfs_root}/lib || mkdir -p ${initramfs_root}/lib
			test -e ${initramfs_root}/lib/`basename ${lib}` || (
				einfo "Adding dynamic library : $lib..."
				$sudo cp -lp $lib ${initramfs_root}/lib
				test -h $lib && $sudo cp -p $(readlink -f $lib) ${initramfs_root}/lib
			)
		done
	fi
}

if [[ -f $source ]]; then
	if [[ -f $target ]] && [[ $(md5sum $source | cut -d " " -f 1) != $(md5sum $target | cut -d " " -f 1) ]]; then ewarn "Looks like we have old copy of '$source'. Upgrading..." && addbin; fi
	if [[ ! -f $target ]]; then addbin; fi
else 
	ewarn "Missing binary: $source, skipping."
fi

#-- vim: tabstop=8
