#!/bin/bash
# better-initramfs project
# https://bitbucket.org/piotrkarbowski/better-initramfs
# Copyright (c) 2010-2013, Piotr Karbowski <piotr.karbowski@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
#    * Redistributions of source code must retain the above copyright notice,
#      this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright notice,
#      this list of conditions and the following disclaimer in the documentation
#      and/or other materials provided with the distribution.
#    * Neither the name of the Piotr Karbowski nor the names of its contributors
#      may be used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE

scriptpath="$(readlink -f "${0}")"
workdir="${scriptpath%/*}"
workdir="$(readlink -f "${workdir}/../")"

arches='i586 x86_64'

die() {
	echo -e "\033[1;30m>\033[0;31m>\033[1;31m> ERROR:\033[0m ${@}" && exit 1
}

einfo() {
	echo -ne "\033[1;30m>\033[0;36m>\033[1;36m> \033[0m${@}\n"
}
ewarn() {
	echo -ne "\033[1;30m>\033[0;33m>\033[1;33m> \033[0m${@}\n"
}

# Get version.
git_tag="$(git describe --tags --exact-match HEAD 2> /dev/null)"
git_branch="$(git symbolic-ref HEAD 2>/dev/null)"
if [ -z "${git_branch}" ]; then die "Not under git?"; fi
git_branch="${git_branch##*/}"

if [ "${git_branch}" = 'master' ] && [ -n "${git_tag}" ]; then
	version="${git_tag}"
else
	git_latestcommit="$(git log -1 --date='short' --format='%h-%ad')"
	version="${git_branch}-${git_latestcommit}"
fi

generate_README.binary() {
	. "${workdir}/bootstrap/bootstrap-all.conf"

	# Dummy functions
	fetch_source() { : ; }
	install_source() { : ; }
	build_source() { : ; }

	echo "Quickstart:"
	echo "	1. gzip initramfs.cpio"
	echo "	2. cp initramfs.cpio.gz /boot"
	echo "	3. Configure bootloader to use initramfs.cpio.gz"
	echo "If your kernel is not gzip compressed, you need to use specified compressor instead of gzip."
	echo "Check your kernel config for CONFIG_KERNEL_GZIP=y, CONFIG_KERNEL_XZ=y, CONFIG_KERNEL_BZIP2=y etc."
	echo
	echo "This binary package contain software under licenses:"
	echo "	better-initramfs-${version} - BSD - https://github.com/slashbeast/better-initramfs"
	for package in ${packages}; do
		( 
			. "${workdir}/bootstrap/lebuilds/${package}.lebuild"
			echo "	${name}-${version} - ${license} - ${homepage}"
		)
	done
	echo
	echo "All built via Aboriginal Linux - http://landley.net/aboriginal/"
}

if ! [ -d "${workdir}/tmp" ]; then
	mkdir "${workdir}/tmp" || die
fi

for arch in ${arches}; do
	build_tmp="$(mktemp -d "${workdir}/tmp/release-${arch}-${version}_XXXXX")"
	if ! [ -d "${build_tmp}" ]; then
		die "Missing build_tmp."
	fi

	# cleanup
	rm -f "${workdir:-/LEFAIL}"/bootstrap/output/*
	rm -f "${workdir:-/LEFAIL}"/output/initramfs.cpio.gz
	rm -f "${workdir:-/LEFAIL}"/sourceroot/bin/{busybox,sh,cryptsetup,lvm,mdadm,dropbearmulti,dropbear,dropbearkey,resume}

	( 
		cd "${workdir}" || die
		bootstrap/bootstrap-all "${arch}" || die "Failed to bootstrap '${arch}' target."

		make prepare
		make image

		cd "${build_tmp:-/INVALID}" || die
		cp "${workdir}"/README.rst .
		cp "${workdir}"/LICENSE .
		cp "${workdir}"/output/initramfs.cpio.gz .
		gunzip initramfs.cpio.gz || die
		generate_README.binary > README.binary

		tarname="${build_tmp##*/}"
		if [ -f "${workdir:-/INVALID}"/output/"${tarname:-INVALID}" ]; then
			rm -f "${workdir:-/INVALID}"/output/"${tarname:-INVALID}"
		fi

		tar -cvf - -C "${workdir:-/INVALID}"/tmp "${tarname:-INVALID}" | bzip2 -9 - > "${workdir}/output/${tarname%_?????}.tar.bz2"

		rm -rf "${build_tmp:-/LEFAIL}"
	) || die "Release failed."


done

